development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefixf: chatapp_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: Assignment5_production
