development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefixf: chatapp_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: Assignment5_production
